export const popularProducts = [
  {
    id: 1,
    name: "Tas Selempang Kulit Asli",
    brand: "LEATHER STUDIO",
    price: "Rp 1.250.000",
    rating: "4.9",
    isNew: true,
    bgColor: "bg-amber-200",
  },
  {
    id: 2,
    name: "Dompet Pria Kulit Sapi",
    brand: "LEATHER STUDIO",
    price: "Rp 450.000",
    originalPrice: "Rp 550.000",
    rating: "4.8",
    discount: "18%",
    bgColor: "bg-blue-200",
  },
  {
    id: 3,
    name: "Ikat Pinggang Premium",
    brand: "LEATHER STUDIO",
    price: "Rp 375.000",
    rating: "4.7",
    bgColor: "bg-rose-200",
  },
  {
    id: 4,
    name: "Sepatu Boots Kulit",
    brand: "LEATHER STUDIO",
    price: "Rp 1.899.000",
    originalPrice: "Rp 2.299.000",
    rating: "4.9",
    discount: "17%",
    bgColor: "bg-emerald-200",
  },
  {
    id: 5,
    name: "Jaket Kulit Motor",
    brand: "LEATHER STUDIO",
    price: "Rp 2.500.000",
    rating: "4.8",
    isNew: true,
    bgColor: "bg-purple-200",
  },
  {
    id: 6,
    name: "Aksesoris Gantungan Kunci",
    brand: "LEATHER STUDIO",
    price: "Rp 120.000",
    rating: "4.6",
    bgColor: "bg-pink-200",
  },
  {
    id: 7,
    name: "Dompet Wanita Kulit Asli",
    brand: "LEATHER STUDIO",
    price: "Rp 495.000",
    rating: "4.9",
    bgColor: "bg-teal-200",
  },
  {
    id: 8,
    name: "Sepatu Casual Pria",
    brand: "LEATHER STUDIO",
    price: "Rp 1.499.000",
    originalPrice: "Rp 1.799.000",
    discount: "17%",
    rating: "4.8",
    bgColor: "bg-yellow-200",
  },
  {
    id: 9,
    name: "Jaket Kulit Wanita",
    brand: "LEATHER STUDIO",
    price: "Rp 2.750.000",
    rating: "4.9",
    isNew: true,
    bgColor: "bg-red-200",
  },
  {
    id: 10,
    name: "Sling Bag Wanita",
    brand: "LEATHER STUDIO",
    price: "Rp 925.000",
    rating: "4.7",
    bgColor: "bg-green-200",
  },
  {
    id: 11,
    name: "Card Holder Minimalis",
    brand: "LEATHER STUDIO",
    price: "Rp 199.000",
    rating: "4.5",
    bgColor: "bg-cyan-200",
  },
  {
    id: 12,
    name: "Sneakers Kulit Premium",
    brand: "LEATHER STUDIO",
    price: "Rp 1.799.000",
    rating: "4.8",
    bgColor: "bg-orange-200",
  },
  {
    id: 13,
    name: "Tas Ransel Kulit",
    brand: "LEATHER STUDIO",
    price: "Rp 1.650.000",
    rating: "4.9",
    bgColor: "bg-lime-200",
  },
  {
    id: 14,
    name: "Dompet Panjang Wanita",
    brand: "LEATHER STUDIO",
    price: "Rp 520.000",
    rating: "4.6",
    bgColor: "bg-fuchsia-200",
  },
  {
    id: 15,
    name: "Sabuk Gesper Besi",
    brand: "LEATHER STUDIO",
    price: "Rp 410.000",
    rating: "4.7",
    bgColor: "bg-indigo-200",
  },
  {
    id: 16,
    name: "Tas Tangan Pria",
    brand: "LEATHER STUDIO",
    price: "Rp 1.200.000",
    rating: "4.8",
    bgColor: "bg-sky-200",
  },
  {
    id: 17,
    name: "Jaket Kasual Kulit",
    brand: "LEATHER STUDIO",
    price: "Rp 2.300.000",
    originalPrice: "Rp 2.700.000",
    discount: "15%",
    rating: "4.7",
    bgColor: "bg-violet-200",
  },
  {
    id: 18,
    name: "Gantungan Kartu Kulit",
    brand: "LEATHER STUDIO",
    price: "Rp 150.000",
    rating: "4.6",
    bgColor: "bg-neutral-200",
  },
  {
    id: 19,
    name: "Loafers Kulit",
    brand: "LEATHER STUDIO",
    price: "Rp 1.550.000",
    rating: "4.9",
    bgColor: "bg-amber-100",
  },
  {
    id: 20,
    name: "Tas Kerja Executive",
    brand: "LEATHER STUDIO",
    price: "Rp 2.100.000",
    rating: "4.8",
    bgColor: "bg-stone-200",
  },
];
