export const productDetails = [
  {
    id: 1,
    name: "Tas Selempang Kulit Asli",
    category: "Aksesoris Pria",
    brand: "LEATHER STUDIO",
    price: "Rp 1.250.000",
    originalPrice: null,
    rating: 4.9,
    reviewCount: 212,
    isNew: true,
    description:
      "Tas selempang kulit asli dari LEATHER STUDIO memberikan kesan maskulin dan elegan. Dibuat dari kulit sapi berkualitas tinggi yang tahan lama, cocok untuk penggunaan harian maupun kerja.",
    images: [
      "https://picsum.photos/seed/tas1/800/800",
      "https://picsum.photos/seed/tas2/800/800",
      "https://picsum.photos/seed/tas3/800/800",
      "https://picsum.photos/seed/tas4/800/800",
    ],
    details: [
      "Material: Kulit sapi asli",
      "Ukuran: 28 x 8 x 20 cm",
      "Berat: 750 gram",
      "Kompartemen: 1 utama, 2 saku kecil",
      "Tali: Dapat disesuaikan dan dilepas",
    ],
    colors: ["Coklat Tua", "Hitam", "Tan"],
    sizes: [],
    inStock: true,
    discount: 0,
  },
  {
    id: 2,
    name: "Dompet Pria Kulit Sapi",
    category: "Dompet",
    brand: "LEATHER STUDIO",
    price: "Rp 450.000",
    originalPrice: "Rp 550.000",
    rating: 4.8,
    reviewCount: 174,
    isNew: false,
    description:
      "Dompet pria elegan dari kulit sapi asli dengan desain minimalis namun fungsional. Dilengkapi banyak slot kartu dan saku uang yang aman.",
    images: [
      "https://picsum.photos/seed/dompet1/800/800",
      "https://picsum.photos/seed/dompet2/800/800",
      "https://picsum.photos/seed/dompet3/800/800",
      "https://picsum.photos/seed/dompet4/800/800",
    ],
    details: [
      "Material: Kulit sapi asli",
      "Ukuran: 11 x 9 x 1.5 cm",
      "Slot: 8 slot kartu, 2 slot uang",
      "Fitur: RFID Protection",
    ],
    colors: ["Hitam", "Coklat"],
    sizes: [],
    inStock: true,
    discount: 18,
  },
  {
    id: 3,
    name: "Ikat Pinggang Premium",
    category: "Aksesoris Pria",
    brand: "LEATHER STUDIO",
    price: "Rp 375.000",
    originalPrice: null,
    rating: 4.7,
    reviewCount: 89,
    isNew: false,
    description:
      "Ikat pinggang kulit asli berkualitas premium dengan gesper logam yang kokoh dan tahan lama. Cocok untuk penampilan formal maupun kasual.",
    images: [
      "https://picsum.photos/seed/belt1/800/800",
      "https://picsum.photos/seed/belt2/800/800",
      "https://picsum.photos/seed/belt3/800/800",
      "https://picsum.photos/seed/belt4/800/800",
    ],
    details: [
      "Material: Kulit sapi & gesper stainless",
      "Lebar: 3.5 cm",
      "Panjang: 110-130 cm (dapat disesuaikan)",
      "Fitur: Anti retak, tahan air",
    ],
    colors: ["Hitam", "Coklat"],
    sizes: ["110cm", "120cm", "130cm"],
    inStock: true,
    discount: 0,
  },
  {
    id: 4,
    name: "Sepatu Boots Kulit",
    category: "Sepatu",
    brand: "LEATHER STUDIO",
    price: "Rp 1.899.000",
    originalPrice: "Rp 2.299.000",
    rating: 4.9,
    reviewCount: 143,
    isNew: false,
    description:
      "Sepatu boots kulit asli dengan desain modern dan sol anti slip. Ideal untuk penggunaan harian maupun touring.",
    images: [
      "https://picsum.photos/seed/boots1/800/800",
      "https://picsum.photos/seed/boots2/800/800",
      "https://picsum.photos/seed/boots3/800/800",
      "https://picsum.photos/seed/boots4/800/800",
    ],
    details: [
      "Material: Kulit sapi asli & sol karet",
      "Ukuran tersedia: 39 - 44",
      "Fitur: Tahan air, breathable lining",
      "Warna: Hitam dan coklat tua",
    ],
    colors: ["Hitam", "Coklat Tua"],
    sizes: ["39", "40", "41", "42", "43", "44"],
    inStock: true,
    discount: 17,
  },
  {
    id: 5,
    name: "Jaket Kulit Motor",
    category: "Fashion Pria",
    brand: "LEATHER STUDIO",
    price: "Rp 2.500.000",
    originalPrice: null,
    rating: 4.8,
    reviewCount: 198,
    isNew: true,
    description:
      "Jaket kulit premium untuk biker sejati. Dirancang dengan lapisan pelindung dan ventilasi udara untuk kenyamanan maksimal saat berkendara.",
    images: [
      "https://picsum.photos/seed/jaket1/800/800",
      "https://picsum.photos/seed/jaket2/800/800",
      "https://picsum.photos/seed/jaket3/800/800",
      "https://picsum.photos/seed/jaket4/800/800",
    ],
    details: [
      "Material: Kulit sapi asli dengan lapisan dalam katun",
      "Ukuran: M, L, XL, XXL",
      "Fitur: Tahan angin, banyak saku, pelindung siku",
      "Warna: Hitam pekat",
    ],
    colors: ["Hitam"],
    sizes: ["M", "L", "XL", "XXL"],
    inStock: true,
    discount: 0,
  },
];
